import random
from random import choice

#OBJECTIVE
#This is a simple way to have a secret Santa event with people that don't have an e-mail (maybe older folks in your family).
#The code is tailored for people who don't know how to access those specific websites made for Secret Santa Events.

#HOW IT WORKS
#It works by using links to images displaying the name of the person you got assigned to.
#Images can be hosted on imgur or any platform you like to use.
#That link must be sent via SMS (or messaging app of choice) to each person by the organizer
#It's nearly impossible to know who the other person chose, so that's not a problem (unless you somehow memorize hyperlinks, which is weird).

#LET'S START
#Here you'll put links to pictures displaying the names of each participant as well as the names themselves.
#Those pictures can be generated by using any photo editing app, such as photoshop or pretty much anything you can find for mobile devices.
#After that, you upload the images to an online platform (Imgur, Google Drive, etc)
#Add or subtract people as needed.

alpha = 'linkA'                       #link to image with their name
c1 = ''                               #name of the person

bravo = 'linkB'                       #link to image with their name
c2 = ''                               #name of the person

charlie = 'linkC'                     #link to image with their name
c3 = ''                               #name of the person       

delta = 'linkD'                       #link to image with their name
c4 = ''                               #name of the person

echo = 'linkE'                        #link to image with their name
c5 = ''                               #name of the person

foxtrot = 'linkF'                     #link to image with their name
c6 = ''                               #name of the person

golf = 'linkG'                        #link to image with their name
c7 = ''                               #name of the person

hotel = 'linkH'                       #link to image with their name
c8 = ''                               #name of the person

india = 'linkI'                       #link to image with their name
c9 = ''                               #name of the person

juliet = 'linkJ'                      #link to image with their name
c10 = ''                              #name of the person

#Here we have a list of all of the people above.
#IMPORTANT: Double check to see if nobody is missing.

people = [alpha,bravo,charlie,delta,echo,foxtrot,golf,hotel,india, juliet]

#People are randomly chosen by the code below. To add people, just copy, paste, change some stuff and ADD EXCEPTIONS FOR the previous person (e.g: x !=p9 ).

#for person 1 (alpha)

p1 = choice([x for x in people if x !=alpha]) #a person cannot choose theirself in the game

#for person 2 (bravo)

p2 = choice([x for x in people if x !=bravo and x !=p1]) #person 2 cannot get the same person as person 1

#person 3 (charlie)

p3 = choice([x for x in people if x !=charlie and x !=p1 and x !=p2]) #and the exceptions just get bigger and bigger

#person 4 (delta)

p4 = choice([x for x in people if x !=delta and x !=p1 and x !=p2 and x !=p3])

#person 5 (echo)

p5 = choice([x for x in people if x !=echo and x !=p1 and x !=p2 and x !=p3 and x !=p4])

#person 6 (foxtrot)

p6 = choice([x for x in people if x !=foxtrot and x !=p1 and x !=p2 and x !=p3 and x !=p4 and x !=p5])

#person 7 (golf)

p7 = choice([x for x in people if x !=golf and x !=p1 and x !=p2 and x !=p3 and x !=p4 and x !=p5 and x !=p6])

#person 8 (hotel)

p8 = choice([x for x in people if x !=hotel and x !=p1 and x !=p2 and x !=p3 and x !=p4 and x !=p5 and x !=p6 and x !=p7])

#person 9 (india)

p9 = choice([x for x in people if x !=india and x !=p1 and x !=p2 and x !=p3 and x !=p4 and x !=p5 and x !=p6 and x !=p7 and x !=p8])

#person 10 (juliet)

p10 = choice([x for x in people if x !=juliet and x !=p1 and x !=p2 and x !=p3 and x !=p4 and x !=p5 and x !=p6 and x !=p7 and x !=p8 and x !=p9])

#The following code will display everybody's names and what link to send to them.
#Yet again, do not forget to add/subtract lines of code depending on the amount of people involved (it's as simple as cppying and pasting, while changing a few characters).

print("send the following links to the following people:")

print()
print(c1,'chose:') # alpha
print(p1)
print('----------------------------')

print()
print(c2,'chose:') #bravo
print(p2)
print('----------------------------')

print()
print(c3,'chose:') #charlie
print(p3)
print('----------------------------')

print()
print(c4,'chose:') #delta
print(p4)
print('----------------------------')

print()
print(c5,'chose:') #echo
print(p5)
print('----------------------------')

print()
print(c6,'chose:') #foxtrot
print(p6)
print('----------------------------')

print()
print(c7,'chose:') #golf
print(p7)
print('----------------------------')

print()
print(c8,'chose:') #hotel
print(p8)
print('----------------------------')

print()
print(c9,'chose:') #india
print(p9)
print('----------------------------')

print()
print('Each link leads to a picture of the name of who they must gift.')
print('Do not click on the links! Only copy and send them to the correct person.')

#AN ERROR! WHY??
#If you get an error, run the code again (it's a rare error that only happens if the last person get's matched with theirself)


#If anything else goes wrong, it's probably your fault.
#Have fun! :D
